### PR TITLE
Android build fixes

### PR DESCRIPTION
**Pull request by lhoward**

### CODE REVIEW

**Review by Lukasa — APPROVED** [review]
Thanks! :sparkles:

**Comment by marcprux** [comment]
@Lukasa Could we have a swift-certificates 1.6.2 patch release that includes this? Android projects that depend on [jwt-kit](https://github.com/vapor/jwt-kit) are currently failing because of this transitive dependency.

**Comment by Lukasa** [comment]
Sure, I can get a release out next week.

**Comment by Lukasa** [comment]
Alrighty, shipped as 1.7.0.

**Pull request merged**
